apiVersion: batch/v1
kind: CronJob
metadata:
  name: misp-cron-feeds-cache-all
  labels:
    app.kubernetes.io/name: misp-cron
spec:
  schedule: "20 2 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: misp-cron
        spec:
          containers:
          - name: curl
            image: registry.gitlab.com/gitlab-ci-utils/curl-jq:3.2.1
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              - 'curl -s -k -X POST -H "Authorization: ${ADMIN_KEY}" -H "Accept: application/json" -H "Content-Type: application/json" https://nginx/feeds/cacheFeeds/all'
            envFrom:
              - secretRef:
                  name: instance-secrets
          restartPolicy: Never
      backoffLimit: 2
      activeDeadlineSeconds: 1200
  concurrencyPolicy: Forbid