{{- if .Values.mariadb.tde.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Release.Name }}-mariadb-tde-keys
  namespace: {{ .Release.Namespace }}
spec:
  type: Opaque
  path: {{ .Values.mariadb.tde.vaultSecretPath}}
  isBinary: true
  keys:
    - {{ .Values.mariadb.tde.randomKeyFilename }}
    - {{ .Values.mariadb.tde.encryptedKeyFilename }}
{{- end }}
