{{- if .Values.misp.vault.enabled }}
{{ range $index, $element := .Values.misp.vault.secrets }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "common.names.fullname" $ }}-{{ $element.destinationname }}
spec:
  type: Opaque
  path: {{ $element.secretmount }}/{{ $element.secretpath }}
{{ end }}
{{ end }}